# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_1_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plugin_3DialogBase(object):
    def setupUi(self, plugin_3DialogBase):
        plugin_3DialogBase.setObjectName("plugin_3DialogBase")
        plugin_3DialogBase.resize(1206, 688)
        self.button_box = QtWidgets.QDialogButtonBox(plugin_3DialogBase)
        self.button_box.setGeometry(QtCore.QRect(180, 340, 801, 361))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.przycisk_przewyzszenie = QtWidgets.QPushButton(plugin_3DialogBase)
        self.przycisk_przewyzszenie.setGeometry(QtCore.QRect(380, 220, 251, 111))
        self.przycisk_przewyzszenie.setObjectName("przycisk_przewyzszenie")
        self.mMapLayerComboBox = QgsMapLayerComboBox(plugin_3DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(80, 70, 241, 111))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label_2 = QtWidgets.QLabel(plugin_3DialogBase)
        self.label_2.setGeometry(QtCore.QRect(110, 230, 211, 81))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(plugin_3DialogBase)
        self.label.setGeometry(QtCore.QRect(100, 380, 231, 51))
        self.label.setObjectName("label")
        self.przycisk_pole_pow = QtWidgets.QPushButton(plugin_3DialogBase)
        self.przycisk_pole_pow.setGeometry(QtCore.QRect(430, 390, 93, 28))
        self.przycisk_pole_pow.setObjectName("przycisk_pole_pow")

        self.retranslateUi(plugin_3DialogBase)
        self.button_box.accepted.connect(plugin_3DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(plugin_3DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(plugin_3DialogBase)

    def retranslateUi(self, plugin_3DialogBase):
        _translate = QtCore.QCoreApplication.translate
        plugin_3DialogBase.setWindowTitle(_translate("plugin_3DialogBase", "plugin"))
        self.przycisk_przewyzszenie.setText(_translate("plugin_3DialogBase", "Kliknij, aby policzyć przewyższenie"))
        self.label_2.setText(_translate("plugin_3DialogBase", "Kliknij, żeby obliczyć przewyższenie"))
        self.label.setText(_translate("plugin_3DialogBase", "Kliknij, żeby obliczyć pole powierzchni"))
        self.przycisk_pole_pow.setText(_translate("plugin_3DialogBase", "PushButton"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    plugin_3DialogBase = QtWidgets.QDialog()
    ui = Ui_plugin_3DialogBase()
    ui.setupUi(plugin_3DialogBase)
    plugin_3DialogBase.show()
    sys.exit(app.exec_())
